[package]
name = "openbaton"
version = "0.1.0"
authors = ["Lorenzo Tomasini <lorenzo.tomasini@gmail.com>"]

[dependencies]
toml = "0.4.5"
log = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
amqp = "0.1.0"
ctrlc = { version = "3.0.3", features = ["termination"] }

